version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image:  circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  
            "app/build.gradle" }}

      - run:
              name: chmod permissions
              command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  
                "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results 

      - run:
          name: Run sonar
          command: ./gradlew sonarqube
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results     

      - run:
          name: Assemble release build
          command: |
            ./gradlew bundleRelease
      - store_artifacts:
          path: app/build/outputs/bundle/release  

    
      - run:
          name: Deploy
          command: |
           ruby --version
           gem install bundler
          
            echo 'source "https://rubygems.org"'>> ./Gemfile && echo 'gem "fastlane"'>> ./Gemfile
           
           
           bundle install
           
           sudo gem install fastlane
            ./gradlew bundleRelease

  

workflows:
  android-build-and-test:
    jobs:
      - build
    
     

           
           
